#Resultsdb_updater template
---
apiVersion: v1
kind: Template
metadata:
  name: resultsdb-updater
parameters:
- name: RESULTSDB_UPDATER_USER_NAME
  displayName: Resultsdb updater user name
  description: Username for resultsdb-updater.py file
  required: true
- name: RESULTSDB_UPDATER_USER_PASSWORD
  displayName: Resultsdb updater user password
  description: Password for resultsdb-updater.py file
  required: true
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata: 
    name: resultdb-updater
  spec:
    replicas: 4
    selector:
      environment: resultsdb-updater
    template:
      metadata:
        labels:
          environment: resultsdb-updater
      spec:
        volumes:
        - name: volume-sl069
          emptyDir: {}
        containers:
        - name: resultsdb-updater
          image: 172.30.1.1:5000/myproject/resultsdb-updater@sha256:fef3bfb41bd97fa548b35e6ccc6ae1db0cd74b674efeaee45d621992de1f2b27
          env: 
          - name: RESULTSDB_USERNAME
            value: "${RESULTSDB_UPDATER_USER_NAME}"
          - name: RESULTSDB_PASSWORD
            value: "${RESULTSDB_UPDATER_USER_PASSWORD}"
          volumeMounts:
          - name: volume-sl069
            mountPath: /etc/resultsdb-updater
